"""empty message

Revision ID: 929edef906ad
Revises: abdc464e4959
Create Date: 2024-09-04 19:10:37.039947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929edef906ad'
down_revision = 'abdc464e4959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_bio', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_bio')
        batch_op.drop_column('user_title')

    # ### end Alembic commands ###
